[versions]
activityCompose = "1.6.1"
androidxTest = "1.1.5"
appCompat = "1.6.0"
composeBom = "2023.01.00"
espresso = "3.5.1"
junit = "4.13.2"
ktxCore = "1.9.0"
lifecycle = "2.5.1"
material = "1.7.0"

[libraries]
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTest" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
junit = { module = "junit:junit", version.ref = "junit" }
